/**
 * generated by Xtext
 */
package hu.bme.mit.mdsd.pineapple.language.validation;

import hu.bme.mit.mdsd.pineapple.language.validation.AbstractDNLanguageValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class DNLanguageValidator extends AbstractDNLanguageValidator {
}
