/*
* generated by Xtext
*/
package hu.bme.mit.mdsd.pineapple.language;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class DNLanguageStandaloneSetup extends DNLanguageStandaloneSetupGenerated{

	public static void doSetup() {
		new DNLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

