/*
 * generated by Xtext
 */
package hu.bme.mit.mdsd.pineapple.language;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DNLanguageRuntimeModule extends hu.bme.mit.mdsd.pineapple.language.AbstractDNLanguageRuntimeModule {

}
