/**
 * generated by Xtext
 */
package hu.bme.mit.mdsd.pineapple.language.serializer;

import hu.bme.mit.mdsd.pineapple.language.serializer.AbstractDNLanguageSemanticSequencer;

@SuppressWarnings("all")
public class DNLanguageSemanticSequencer extends AbstractDNLanguageSemanticSequencer {
}
