/**
 * generated by Xtext
 */
package hu.bme.mit.mdsd.pineapple.language.serializer;

import hu.bme.mit.mdsd.pineapple.language.serializer.AbstractDNLanguageSyntacticSequencer;

@SuppressWarnings("all")
public class DNLanguageSyntacticSequencer extends AbstractDNLanguageSyntacticSequencer {
}
