/*
* generated by Xtext
*/
package hu.bme.mit.mdsd.pineapple.language.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import hu.bme.mit.mdsd.pineapple.language.services.DNLanguageGrammarAccess;

public class DNLanguageParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private DNLanguageGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected hu.bme.mit.mdsd.pineapple.language.parser.antlr.internal.InternalDNLanguageParser createParser(XtextTokenStream stream) {
		return new hu.bme.mit.mdsd.pineapple.language.parser.antlr.internal.InternalDNLanguageParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "DataflowSystem";
	}
	
	public DNLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DNLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
