/*
 * generated by Xtext
 */
package hu.bme.mit.mdsd.pineapple.language.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractDNLanguageValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://dataflownet/1.0"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://typehierarchy/1.0"));
		return result;
	}
}
